const data = {
	products: [
		{
			name: "Nike Slim Shirt",
			slug: "nike-slim-shirt",
			category: "Shirt",
			image: "/images/p1.jpg",
			price: 120,
			countInStock: 10,
			brand: "Nike",
			rating: 4.5,
			numReview: 10,
			description: "high quality shirt",
		},
		{
			name: "Addidas Fit Shirt",
			slug: "addidas-fit-shirt",
			category: "Shirt",
			image: "/images/p2.jpg",
			price: 190,
			countInStock: 20,
			brand: "Nike",
			rating: 4.5,
			numReview: 10,
			description: "high quality shirt",
		},
		{
			name: "Nike Slim Pant",
			slug: "nike-slim-pant",
			category: "Shirt",
			image: "/images/p3.jpg",
			price: 60,
			countInStock: 15,
			brand: "Nike",
			rating: 4.5,
			numReview: 10,
			description: "high quality shirt",
		},
		{
			name: "Addidas Slim Pant",
			slug: "addidas-slim-pant",
			category: "Shirt",
			image: "/images/p4.jpg",
			price: 60,
			countInStock: 5,
			brand: "Nike",
			rating: 4.5,
			numReview: 10,
			description: "high quality shirt",
		},
	],
};
export default data;
